### ISSUE TITLE
Pepe

### ISSUE THREAD

**Issue by Ferreyra978** [XTRATEXTURE/Auto-hatch-pet-simualtor-1#1]
Plis how use this hack?

**Comment by annemarieshev** [comment]
What do you mean ?

**Comment by Ferreyra978** [comment]
What i need to do to use this

**Comment by annemarieshev** [comment]
To use Pepe right ?

**Comment by Ferreyra978** [comment]
To use the auto hatch

**Comment by Ferreyra978** [comment]
☝🏻🤓

**Comment by annemarieshev** [comment]
Okay do you have an issues ?

**Comment by Ferreyra978** [comment]
I dont know im new

**Comment by Ferreyra978** [comment]
Im new and i want to use the auto hatch

**Comment by annemarieshev** [comment]
That why I ask did you have any problems or any issues with your wallet,coin  or Pepe account?

**Comment by Ferreyra978** [comment]
No but i want use this auto hatch. You know how i can?

**Comment by Ferreyra978** [comment]
I dont nkow to use

**Comment by XTRATEXTURE** [comment]
I didnt update it
